apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: student-d-altenhofer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/pickngo-dave/frontend
          ports:
            - containerPort: 4200
          env:
            - name: BASE_URL
              value: '/d.altenhofer/'
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: student-d-altenhofer
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: db
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: student-d-altenhofer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /d.altenhofer/(.*)$
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
