apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: student-d-altenhofer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/pickngo-dave/backend
          ports:
            - containerPort: 8080
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_BASE_HREF
              value: "/api/"
            - name: APP_FORWARDED
              value: "true"
            - name: DB_HOST
              value: "database-svc.student-d-altenhofer"
            - name: DB_USER
              value: "app"
            - name: DB_PASS
              value: "app"
            - name: DB_NAME
              value: "app"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: student-d-altenhofer
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: backend
