version: '3.7'

services:
  postgres-dev:
    image: postgres:latest
    container_name: pickngo-db
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
      - ./db/:/var/lib/postgresql/pickngo-data
    ports:
      - "5432:5432"
  frontend:
    image: pickngo/frontend-dev
    container_name: pickngo-frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
  backend:
    image: pickngo/backend-dev
    container_name: pickngo-backend
    depends_on:
      - postgres-dev
    ports:
      - "8080:8080"
    links:
      - postgres-dev:db
    volumes:
      - ./backend:/backend
      - ./maven-cache:/root/.m2
    environment:
      APP_HOST: 0.0.0.0
      DB_HOST: db
      DB_NAME: db
      DB_USER: app
      DB_PASS: app